# -*- coding: utf-8 -*-
"""Copy of Fine_Tuning_LLama_Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plqLPA3oIBuFIisX6W8tfe4gB7vhCMsa
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import torch
# major_version, minor_version = torch.cuda.get_device_capability()
# !pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
# if major_version >= 8:
#     !pip install --no-deps packaging ninja einops flash-attn xformers trl peft accelerate bitsandbytes
# else:
#     !pip install --no-deps xformers trl peft accelerate bitsandbytes
# pass

"""Next we need to prepare to load a range of quantized language models, including a new 15 trillion token LLama-3 model, optimized for memory efficiency with 4-bit quantization.

"""

from unsloth import FastLanguageModel
import torch
max_seq_length = 2048
dtype = None
load_in_4bit = True

fourbit_models = [
    "unsloth/mistral-7b-bnb-4bit",
    "unsloth/mistral-7b-instruct-v0.2-bnb-4bit",
    "unsloth/llama-2-7b-bnb-4bit",
    "unsloth/gemma-7b-bnb-4bit",
    "unsloth/gemma-7b-it-bnb-4bit",
    "unsloth/gemma-2b-bnb-4bit",
    "unsloth/gemma-2b-it-bnb-4bit",
    "unsloth/llama-3-8b-bnb-4bit",
]

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-bnb-4bit", # Llama-3 70b also works
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

"""---

Next, we integrate LoRA adapters into our model, which allows us to efficiently update just a fraction of the model's parameters, enhancing training speed and reducing computational load.
"""

model = FastLanguageModel.get_peft_model(
    model,
    r = 16, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
    loftq_config = None,
)

"""<a name="Data"></a>
### Data Prep
We now use the Alpaca dataset from [yahma](https://huggingface.co/datasets/yahma/alpaca-cleaned), which is a filtered version of 52K of the original [Alpaca dataset](https://crfm.stanford.edu/2023/03/13/alpaca.html). You can replace this code section with your own data prep.

Then, we define a system prompt that formats tasks into instructions, inputs, and responses, and apply it to a dataset to prepare our inputs and outputs for the model, with an EOS token to signal completion.

"""

# this is basically the system prompt
alpaca_prompt = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### instruction:
{}

### input:
{}

### response:
{}"""

EOS_TOKEN = tokenizer.eos_token # do not forget this part!
def formatting_prompts_func(examples):
    instructions = examples["instruction"]
    inputs       = examples["input"]
    responses      = examples["response"]
    texts = []
    for instruction, input, response in zip(instructions, inputs, responses):
        text = alpaca_prompt.format(instruction, input, response) + EOS_TOKEN # without this token generation goes on forever!
        texts.append(text)
    return { "text" : texts, }
pass

# from datasets import load_dataset
# dataset = load_dataset("json", data_files="/content/drive/MyDrive/Capstone/final_data_updated.json", split="train")
# dataset = dataset.map(formatting_prompts_func, batched = True,)

from datasets import load_dataset, concatenate_datasets

dataset1 = load_dataset("json", data_files="/content/drive/MyDrive/Capstone/final_multi_turn_data.json", split="train")
dataset1 = dataset1.map(formatting_prompts_func, batched=True)

dataset2 = load_dataset("json", data_files="/content/drive/MyDrive/Capstone/final_multi_turn_data-v2.json", split="train")
dataset2 = dataset2.map(formatting_prompts_func, batched=True)

#Concatenate the two datasets
dataset = concatenate_datasets([dataset1, dataset2])

len(dataset)

"""<a name="Train"></a>
### Train the model
- We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.
- At this stage, we're configuring our model's training setup, where we define things like batch size and learning rate, to teach our model effectively with the data we have prepared.
"""

from trl import SFTTrainer
from transformers import TrainingArguments

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    formatting_func = formatting_prompts_func,
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 500, # increase this to make the model learn "better"
        num_train_epochs=4,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

#@title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

# We're now kicking off the actual training of our model, which will spit out some statistics showing us how well it learns
trainer_stats = trainer.train()

"""<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!

You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!
"""

instruction = (
    "You are a professional 911 dispatcher trained to handle emergency calls "
    "with clarity, calm, and efficiency. Follow proper emergency protocols while "
    "keeping the conversation natural and efficient. Do not waste time, be as optimal "
    "as possible in gathering key information and dispatching help."
)

emergency_calls = [
    "Somebody's been shot! He's not moving!",
    "The roof just blew off our house, we’re trapped inside!",
    "Water is rising fast, we’re stuck on the second floor!",
    "The fire’s getting close to our neighborhood—we need to evacuate!",
    "Our building collapsed —someone’s stuck under rubble!",
    "There’s ash falling everywhere, and people are choking—we don’t know where to go!",
    "We were hiking and my friend slipped and hit her head. She’s bleeding a lot.",
    "There’s a woman screaming in the park. I think she’s being attacked.",
    "I just witnessed a car crash, and one of the drivers looks unconscious.",
    "My dad just collapsed. He’s not breathing!",
    "There’s a man trying to break into my apartment right now!",
    "My house is on fire, and my kids are inside!"
]

log_file = "DispatcherLLM_responses.txt"

FastLanguageModel.for_inference(model)
inputs = tokenizer(
[
    alpaca_prompt.format(
        "You are a professional 911 dispatcher trained to handle emergency calls with clarity, calm, and efficiency. Follow proper emergency protocols while keeping the conversation natural and efficient. Do not waste time, be as optimal as possible in gathering key information and dispatching help.",
        "Somebody's been shot! He's not moving!", # input
        "", # output - leave this blank for generation!
    )
], return_tensors = "pt").to("cuda")

from transformers import TextStreamer
text_streamer = TextStreamer(tokenizer)
_ = model.generate(**inputs, streamer = text_streamer, max_new_tokens = 128)

text_streamer = TextStreamer(tokenizer)

with open(log_file, "w", encoding="utf-8") as f:
    for i, user_input in enumerate(emergency_calls, 1):
        # Format the full prompt for model input
        prompt = alpaca_prompt.format(instruction, user_input, "")
        inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

        # Generate response
        generated_ids = model.generate(**inputs, max_new_tokens=128)
        output = tokenizer.decode(generated_ids[0], skip_special_tokens=True)

        # Extract only the dispatcher response
        if "### Response:" in output:
            response = output.split("### Response:")[-1].strip()
        elif "### response:" in output:
            response = output.split("### response:")[-1].strip()
        else:
            # fallback in case format is off
            response = output.strip()

        # Print to console
        print(f"\nCall #{i}: {user_input}")
        print(f"Dispatcher Response: {response}")

        # Write to file
        f.write(f"--- Call {i} ---\n")
        f.write(f"Input: {user_input}\n")
        f.write(f"Dispatcher Response:\n{response}\n\n")

"""<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!
"""

# model.save_pretrained("/content/drive/MyDrive/Capstone/lora_model_multiturn_2") # Local saving
# tokenizer.save_pretrained("/content/drive/MyDrive/Capstone/lora_model_multiturn_2")
# # model.push_to_hub("your_name/lora_model", token = "...") # Online saving
# # Merge LoRA adapter into base model and save as a standalone model
model.merge_and_save("/content/drive/MyDrive/Capstone/merged_full_model")

# Also save the tokenizer (important!)
tokenizer.save_pretrained("/content/drive/MyDrive/Capstone/merged_full_model")



"""Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:"""

if True:   #Change to True for loading model
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "/content/drive/MyDrive/Capstone/lora_model2",
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
    )
    FastLanguageModel.for_inference(model)

# alpaca_prompt = You MUST run cells from above!

inputs = tokenizer(
[
    alpaca_prompt.format(
        instruction,
        "Water is rising fast, we’re stuck on the second floor!",
        "",
    )
], return_tensors = "pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens = 64, use_cache = True)
tokenizer.batch_decode(outputs)

def build_prompt(instruction, input_text, output_text=""):
    return alpaca_prompt.format(instruction, input_text, output_text)

while True:
    user_input = input("\n👤 Caller: ")

    if user_input.lower() in ["exit", "quit","Bye"]:
        print("🔚 Ending conversation.")
        break

    prompt = build_prompt(instruction, user_input)
    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    outputs = model.generate(**inputs, max_new_tokens=64, use_cache=True)
    raw_output = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    if "### response:" in raw_output:
      response_text = raw_output.split("### response:")[1].strip()
    else:
      response_text = raw_output.strip()
    print(f"👮 Dispatcher:{response_text}")

# Initial instruction
instruction = (
    "You are a professional 911 dispatcher trained to handle emergency calls "
    "with clarity, calm, and efficiency. Follow proper emergency protocols while "
    "keeping the conversation natural and efficient. Do not waste time, be as optimal "
    "as possible in gathering key information and dispatching help."
)

# Alpaca-style template
def build_prompt(instruction, conversation):
    return (
        "Below is an instruction that describes a task, paired with an input that provides further context. "
        "Write a response that appropriately completes the request.\n\n"
        f"### instruction:\n{instruction}\n\n"
        f"### input:\n{conversation}\n\n"
        "### response:\n"
    )

# Initialize conversation memory
conversation = ""

print("📞 911 Dispatcher is now live. Type 'exit' to end the call.\n")

while True:
    user_input = input("👤 User: ")

    if user_input.strip().lower() in ["exit", "quit"]:
        print("🔚 Ending call.")
        break

    conversation += f"user: {user_input}\n"

    # Format the full prompt with history
    prompt = build_prompt(instruction, conversation)

    # Tokenize and send to CUDA
    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    # Generate model output
    outputs = model.generate(**inputs, max_new_tokens=128, use_cache=True)
    raw_output = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

    # Extract just the response text
    if "### response:" in raw_output:
        response_text = raw_output.split("### response:")[1].strip()
    else:
        response_text = raw_output.strip()

    # Add the model's response to the conversation
    conversation += f"Assistant {response_text}\n"

    # Print the response
    print(f"🧑‍✈️ Dispatcher: {response_text}")

print(conversation)

# Updated 911 Dispatcher Simulation Script

import json

# Initial instruction
instruction = (
    "You are a professional 911 dispatcher. Your role is to respond to emergency calls "
    "with clarity, calm, and efficiency. You will handle these calls by following proper emergency protocols "
    "while maintaining a natural and effective conversation. The 'user' is the person in distress who has called 911, "
    "and your role as the assistant is to act as the dispatcher, guiding them through the situation and collecting the "
    "necessary information. Be concise, focused, and ensure the user feels supported while dispatching help as quickly as possible."
)

# Initialize list of conversation turns
conversation_history = []

def build_prompt(instruction, turns):
    # Format the conversation in JSON-like input list as your fine-tuning data
    formatted_input = json.dumps(turns, indent=2)
    return (
        f'{{\n'
        f'  "instruction": "{instruction}",\n'
        f'  "input": {formatted_input},\n'
        f'  "response": {{\n    "role": "assistant",\n    "content": '
    )

print("📞 911 Dispatcher is now live. Type 'exit' to end the call.\n")

while True:
    user_input = input("👤 User: ")

    if user_input.strip().lower() in ["exit", "quit"]:
        print("🔚 Ending call.")
        break

    # Add the new user message to the conversation history
    conversation_history.append({"role": "user", "content": user_input})

    # Format the full prompt for the model
    prompt_start = build_prompt(instruction, conversation_history)
    prompt = prompt_start  # We’ll append response closing quote after model generation

    # Tokenize and send to model
    inputs = tokenizer([prompt], return_tensors="pt").to("cuda")

    # Generate the model's response
    outputs = model.generate(
        **inputs,
        max_new_tokens=128,
        pad_token_id=tokenizer.eos_token_id,
        use_cache=True
    )
    raw_output = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    print(raw_output)
    # # Extract the part after the opening `"content": "` in the model response
    # if '"content":' in raw_output:
    #     try:
    #         response_text = raw_output.split('"content":')[1].strip()
    #         if response_text.startswith('"'):
    #             response_text = response_text[1:]
    #         if response_text.endswith('"}'):
    #             response_text = response_text[:-2]
    #         elif response_text.endswith('"'):
    #             response_text = response_text[:-1]
    #     except Exception:
    #         response_text = raw_output.strip()
    # else:
    #     response_text = raw_output.strip()

    # # Add assistant response to history
    # conversation_history.append({"role": "assistant", "content": response_text})

    # # Display the assistant response
    # print(f"🧑‍✈️ Dispatcher: {response_text}")

conversation_history