# -*- coding: utf-8 -*-
"""Nerbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wieqasXR8oXswMJ5Mpyh2nyroHADA0p
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install transformers torch pandas

from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
import pandas as pd

# Load lightweight NER model
model_name = "dslim/bert-base-NER"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer, aggregation_strategy="simple")

# Read file in chunks (to avoid memory issues)
chunksize = 1000
input_file = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_final_data.tsv"


results = []

for chunk in pd.read_csv(input_file, sep="\t", chunksize=chunksize):
    for text in chunk["tweet_text"]:
        try:
            entities = ner_pipeline(text)
            locs = [
                ent['word'] for ent in entities
                if ent['entity_group'] in ["LOC", "PER", "ORG"] or ent['entity_group']=="MISC"
                and ent['entity_group'] == "LOC"
            ]
        except:
            locs = []

        results.append(",".join(locs) if locs else "")

output_file = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_LRR.tsv"

results

type(results)

import re
def normalize_location(loc):
    if not isinstance(loc, str) or loc.strip().lower() == "nan":
        return "Unknown"
    # Remove hashtags, numbers, punctuation, etc.
    loc = re.sub(r"[^a-zA-Z\s,]", "", loc)
    # Split on commas and deduplicate segments
    parts = [p.strip().title() for p in loc.split(",") if p.strip()]
    parts = list(dict.fromkeys(parts))  # preserve order but remove duplicates
    # Join normalized components
    normalized = ", ".join(parts)
    # Handle incomplete tokens
    if not normalized:
        normalized = "Unknown"
    return normalized

normalized_results = [normalize_location(loc) for loc in results]

# save results
df = pd.read_csv(input_file, sep="\t")
df["extracted_locations"] = normalized_results
df.to_csv(output_file, sep="\t", index=False)

print("✅ Extraction complete:", output_file)

#from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
#import pandas as pd

# High accuracy location NER model
'''model_name = "ml6team/bert-base-uncased-city-country-ner"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

loc_pipeline = pipeline(
    "ner",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",
    device=0   # CPU; change to 0 if GPU available
)

'''



'''output_locations = []

def extract_locations(text):
    try:
        ents = loc_pipeline(text)
        locs = [e["word"] for e in ents if e["entity_group"] in ["LOC", "GPE"]]
        return ",".join(locs)
    except:
        return ""

for chunk in pd.read_csv(input_file, sep="\t", chunksize=chunksize):
    chunk["extracted_locations"] = chunk["tweet_text"].apply(extract_locations)
    output_locations.append(chunk)

output_locations

