# -*- coding: utf-8 -*-
"""RAG_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGsGidQtRqzo2A9pG5eGLm9wzWLKjec7
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# import torch
# major_version, minor_version = torch.cuda.get_device_capability()
# !pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
# if major_version >= 8:
#     !pip install --no-deps packaging ninja einops flash-attn xformers trl peft accelerate bitsandbytes
# else:
#     !pip install --no-deps xformers trl peft accelerate bitsandbytes
# pass

!pip install chromadb

pip install -q ragas datasets evaluate chromadb sentence-transformers

import os
import re
import numpy as np
import pandas as pd
from typing import List, Dict
import chromadb
from sentence_transformers import SentenceTransformer, util
import torch
from tqdm import tqdm

# ============================================================================
# 2. HELPER FUNCTIONS (from your notebook)
# ============================================================================

def normalize_location_for_filter(loc):
    """Match your ingestion normalization (Title Case pieces, commas)."""
    if not isinstance(loc, str) or not loc.strip():
        return None
    loc = re.sub(r"[^a-zA-Z\s,]", "", loc)
    parts = [p.strip().title() for p in loc.split(",") if p.strip()]
    if not parts:
        return None
    # de-dupe preserving order
    seen = set()
    norm_parts = []
    for p in parts:
        if p not in seen:
            seen.add(p)
            norm_parts.append(p)
    return ", ".join(norm_parts)

def infer_image_damage_and_info(entry):
    """Infer damage level from tweet text"""
    text = str(entry.get("tweet_text", "")).lower()

    high_kw = [
                    "trapped", "on fire", "engulfed", "destroyed", "collapse", "evacuate",
                    "urgent", "immediate", "fatal", "dead", "massive destruction",
                    "completely ruined", "severe damage", "multiple casualties", "devastated",
                    "widespread damage", "catastrophic", "total loss", "building down",
                    "major explosion", "severely injured", "life threatening", "critical condition",
                    "missing persons", "under rubble", "burning intensely", "structure failure",
                    "blocked exits", "panic", "chaos", "major incident", "emergency declared",
                    "disaster", "crumbling", "collapsed structure", "entire area destroyed",
                    "fatalities reported", "serious casualties", "fire out of control",
                    "complete destruction", "total devastation", "significant structural failure",
                    "building leveled", "road washed away", "bridge collapsed"
    ]

    med_kw = [
                    "burn", "burned", "smoke", "injured", "damage", "collapsed",
                    "heavy smoke", "partially destroyed", "serious", "severe", "moderate damage",
                    "some injuries", "partially collapsed", "significant damage",
                    "building cracked", "fire spreading", "visible flames", "strong winds",
                    "minor casualties", "loss of power", "roof damaged", "wall down",
                    "street flooded", "partial evacuation", "hazardous", "unstable structure",
                    "property damage", "broken windows", "fallen debris", "injuries reported",
                    "medium intensity", "some people hurt", "moderate flooding",
                    "sections destroyed", "structural damage", "roads blocked", "trees down"
    ]
    low_kw = [
                    "small", "minor", "contained", "controlled", "smouldering", "smoldering",
                    "under control", "limited", "localized", "light damage", "no injuries",
                    "contained fire", "low intensity", "minor flooding", "slight damage",
                    "no casualties", "safe", "situation stable", "partly controlled",
                    "handled", "manageable", "contained incident", "non-critical",
                    "minor issue", "resolved", "contained quickly", "smoke subsiding",
                    "power restored", "roads cleared", "clean-up ongoing"
    ]

    if any(k in text for k in high_kw):
        damage = "HIGH"
    elif any(k in text for k in med_kw):
        damage = "MEDIUM"
    elif any(k in text for k in low_kw):
        damage = "LOW"
    else:
        damage = "UNKNOWN"

    cap = str(entry.get("image_caption", "")).strip()
    info = "NOT INFORMATIVE" if len(cap) == 0 else "INFORMATIVE"

    return damage, info

# ============================================================================
# 3. RETRIEVAL SYSTEM (from your notebook)
# ============================================================================

class RetrievalConfig:
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    TOP_K = 5
    IMAGE_BASE_PATH = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD"
    RETURN_IMAGES = False
    MAX_ITEM_CHARS = 200
    HISTORY_TURNS = 4

class RetrievalSystem:
    """Handles vector similarity search with ChromaDB"""

    def __init__(self, collection, clip_model, config):
        self.collection = collection
        self.clip_model = clip_model
        self.config = config

    def encode_text(self, query_text: str) -> List[float]:
        """Encode query text into CLIP embedding"""
        emb = self.clip_model.encode(
            [query_text],
            convert_to_tensor=True,
            device=self.config.DEVICE,
        )
        return emb[0].detach().cpu().tolist()

    def _query_chroma(self, query_embedding, n_results, where=None):
        return self.collection.query(
            query_embeddings=[query_embedding],
            n_results=n_results,
            include=["documents", "metadatas", "distances"],
            where=where or None,
        )

    def _postprocess(self, results: Dict, limit: int) -> List[Dict]:
        """Normalize Chroma results"""
        out = []
        if not results or not results.get("documents"):
            return out

        documents = (results.get("documents") or [[]])[0][:limit]
        metadatas = (results.get("metadatas") or [[]])[0][:limit]
        distances = (results.get("distances") or [[]])[0][:limit]
        ids = (results.get("ids") or [[]])[0][:limit]

        for doc, meta, distance, doc_id in zip(documents, metadatas, distances, ids):
            meta = meta or {}
            image_path_from_meta = meta.get("image_path", "")
            image_id = None
            if image_path_from_meta:
                image_filename = image_path_from_meta.split("/")[-1]
                image_id = image_filename.rsplit(".", 1)[0]

            score = 1.0 - float(distance) if distance is not None else 0.0

            out.append({
                "id": doc_id,
                "tweet_text": doc or "",
                "tweet_id": image_id.split("_")[0] if image_id else "unknown",
                "image_id": image_id,
                "disaster_type": meta.get("disaster_type", "Unknown"),
                "extracted_location": meta.get("extracted_location", ""),
                "source_file": meta.get("source_file", ""),
                "score": score,
                "image_caption": doc or "",
                "image_damage": None,
                "image_info": None,
            })
        return out

    def retrieve_topk(self, query: str, top_k: int = None) -> List[Dict]:
        """Retrieve top-k similar items from ChromaDB"""
        if top_k is None:
            top_k = self.config.TOP_K

        try:
            qvec = self.encode_text(query)
            results = self._query_chroma(qvec, n_results=top_k)
            return self._postprocess(results, top_k)
        except Exception as e:
            print(f"Error querying ChromaDB: {e}")
            return []

# ============================================================================
# 4. RESPONSE GENERATOR (from your notebook)
# ============================================================================

class ResponseGenerator:
    """Generates dispatcher responses using fine-tuned model"""

    def __init__(self, model, tokenizer, config):
        self.model = model
        self.tokenizer = tokenizer
        self.config = config

    def generate_response(self, user_input, retrieved_results, conversation_history):
        """Generate dispatcher response"""
        if self.model is None or self.tokenizer is None:
            return self._generate_fallback_response(user_input, conversation_history)

        context_block = self._format_retrieved_context(retrieved_results)
        hist_text = self._format_conversation_history(conversation_history)
        prompt = self._build_prompt(user_input, context_block, hist_text)

        try:
            inputs = self.tokenizer([prompt], return_tensors="pt").to(self.config.DEVICE)

            with torch.no_grad():
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=256,
                    use_cache=True,
                    do_sample=True,
                    temperature=0.7,
                    pad_token_id=self.tokenizer.eos_token_id
                )

            raw = self.tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]

            if "### response:" in raw:
                return raw.split("### response:")[1].strip()
            return raw.strip()

        except Exception as e:
            print(f"Error generating response: {e}")
            return self._generate_fallback_response(user_input, conversation_history)

    def _format_retrieved_context(self, retrieved_results):
        """Format retrieved results for prompt"""
        context_blocks = []
        for i, r in enumerate(retrieved_results, start=1):
            tweet = (r.get("tweet_text","") or "").strip()
            tweet_short = (tweet[:self.config.MAX_ITEM_CHARS] +
                          ("…" if len(tweet) > self.config.MAX_ITEM_CHARS else ""))

            damage, info = infer_image_damage_and_info(r)

            block = (
                f"Item {i}:\n"
                f" disaster_type: {r.get('disaster_type','')}\n"
                f" location: {r.get('extracted_location','')}\n"
                f" image_damage: {damage}\n"
                f" tweet_text: {tweet_short}\n"
                f" retrieval_score: {r.get('score', 0):.4f}\n"
            )
            context_blocks.append(block)

        return "\n".join(context_blocks) if context_blocks else "No retrieved items."

    def _format_conversation_history(self, conversation_history):
        """Format conversation history for prompt"""
        hist_snippet = []
        for role, text in conversation_history[-self.config.HISTORY_TURNS:]:
            prefix = "User:" if role == "user" else "Assistant:"
            hist_snippet.append(f"{prefix} {text}")
        return "\n".join(hist_snippet) if hist_snippet else "[no earlier turns]"

    def _build_prompt(self, user_input, context_block, hist_text):
        """Build complete prompt for model"""
        instruction = (
            "You are a professional 911 dispatcher. You have access to historical crisis data and conversation history. "
            "IMPORTANT: Read and use the retrieved context and conversation history to provide relevant, progressive responses. "
            "Do NOT repeat the same questions. Build on what the caller has already told you. "
            "If the caller has provided location information, acknowledge it and ask for the next most critical details "
            "(exact address/landmarks, number of people involved, injuries, immediate dangers, escape routes). "
            "Be efficient, calm, and move the conversation forward to dispatch appropriate help."
        )

        conversation_input = (
            f"CONVERSATION HISTORY - READ THIS CAREFULLY:\n{hist_text}\n\n"
            "RETRIEVED CRISIS CONTEXT:\n"
            f"{context_block}\n\n"
            "CURRENT USER MESSAGE:\n"
            f"{user_input}\n\n"
            "CRITICAL INSTRUCTIONS: This is a continuing conversation. The user has already provided information above. "
            "Do NOT ask questions they've already answered. Progress the conversation by asking for the next most important details needed for dispatch."
        )

        return (
            "Below is an instruction that describes a task, paired with an input that provides further context. "
            "Write a response that appropriately completes the request.\n\n"
            f"### instruction:\n{instruction}\n\n"
            f"### input:\n{conversation_input}\n\n"
            "### response:\n"
        )

    def _generate_fallback_response(self, user_input, conversation_history):
        """Generate rule-based response when model isn't available"""
        user_lower = user_input.lower()

        if "fire" in user_lower or "wildfire" in user_lower:
            return "I'm dispatching fire and rescue to your location. Are you in immediate danger? Do you have a safe evacuation route?"
        elif "flood" in user_lower or "water" in user_lower:
            return "I'm dispatching emergency services. Can you get to higher ground? How many people are with you?"
        elif "earthquake" in user_lower or "collapsed" in user_lower:
            return "I'm dispatching rescue teams. Are you trapped? Are there injuries?"

        return "I'm getting help to you right away. What is your exact location?"

# ============================================================================
# 5. INITIALIZE SYSTEM COMPONENTS
# ============================================================================

print("🚀 Initializing RAG System...")

# ChromaDB setup
CHROMA_PATH = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/chromadb_store_multimodal"
COLLECTION_NAME = "crisis_multimodal"

client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = client.get_collection(COLLECTION_NAME)

# Load CLIP model
device = "cuda" if torch.cuda.is_available() else "cpu"
clip_model = SentenceTransformer("clip-ViT-B-32").to(device)

# Load config
config = RetrievalConfig()
config.DEVICE = device

# Initialize retrieval system
retrieval_system = RetrievalSystem(
    collection=collection,
    clip_model=clip_model,
    config=config
)

# Load LLM model (Unsloth LoRA)
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/Capstone/lora_model2",
    max_seq_length=2048,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

# Initialize response generator
response_generator = ResponseGenerator(
    model=model,
    tokenizer=tokenizer,
    config=config
)

print("✅ All components loaded successfully!")
print(f"📊 ChromaDB collection size: {collection.count()} documents")

# ============================================================================
# 6. TEST DATASET - ENHANCED WITH YOUR EXAMPLES
# ============================================================================

test_queries = [
    {
        "question": "911, please help—streets are underwater in Colombo and our ground floor is flooding. Power is out and water is rising fast.",
        "ground_truth": "Severe flooding in Colombo causing rising water inside homes and power outage.",
        "location": "Colombo",
        "disaster_type": "flood",
        "expected_keywords": ["flood", "colombo", "water", "rising"]
    },
    {
        "question": "There was a strong earthquake in Mexico City—my apartment walls cracked and the staircase collapsed. People are trapped.",
        "ground_truth": "Earthquake in Mexico City with structural damage including cracked walls and collapsed staircase; people potentially trapped.",
        "location": "Mexico City",
        "disaster_type": "earthquake",
        "expected_keywords": ["earthquake", "mexico", "collapsed", "trapped"]
    },
    {
        "question": "We can see flames coming over the hill in Santa Rosa—wildfire ash is falling and we're choking on smoke. Do we evacuate now?",
        "ground_truth": "Wildfire approaching Santa Rosa with heavy smoke and ash, posing immediate evacuation concerns.",
        "location": "Santa Rosa",
        "disaster_type": "wildfire",
        "expected_keywords": ["wildfire", "santa rosa", "fire", "smoke", "evacuate"]
    },
    {
        "question": "What areas in California are affected by wildfires?",
        "ground_truth": "Santa Rosa, Napa Valley, and surrounding areas in California are affected by wildfires.",
        "location": "California",
        "disaster_type": "wildfire",
        "expected_keywords": ["california", "fire", "wildfire", "santa rosa"]
    },
    {
    "question": "Heavy rain in Colombo again—drains are overflowing and cars are submerged up to the windows. People are stranded on rooftops.",
    "ground_truth": "Severe flooding in Colombo with overflowing drains, submerged vehicles, and stranded residents.",
    "location": "Colombo",
    "disaster_type": "flood",
    "expected_keywords": ["flood", "colombo", "rain", "submerged", "rooftops"]
    },
    {
        "question": "Another aftershock in Mexico City just hit—more cracks are forming in the walls and debris is falling from the ceiling.",
        "ground_truth": "Earthquake aftershock in Mexico City causing additional structural cracks and falling debris.",
        "location": "Mexico City",
        "disaster_type": "earthquake",
        "expected_keywords": ["earthquake", "mexico city", "aftershock", "cracks", "debris"]
    },
    {
        "question": "Smoke in Santa Rosa is getting worse—the wildfire wind shifted and ash is covering our entire neighborhood.",
        "ground_truth": "Wildfire near Santa Rosa causing worsening smoke and ashfall due to shifting winds.",
        "location": "Santa Rosa",
        "disaster_type": "wildfire",
        "expected_keywords": ["wildfire", "santa rosa", "smoke", "ash", "wind"]
    },
    {
        "question": "Wildfires continue to spread across California—are Napa Valley and nearby regions still under evacuation alerts?",
        "ground_truth": "Wildfires in California affecting regions including Napa Valley, which remain under evacuation alerts.",
        "location": "California",
        "disaster_type": "wildfire",
        "expected_keywords": ["california", "wildfire", "napa", "evacuation", "spread"]
    }

]



print(f"\n📊 Test Dataset: {len(test_queries)} queries")

# ============================================================================
# 7. RETRIEVAL AND RESPONSE GENERATION
# ============================================================================

print("\n🔍 Retrieving contexts and generating responses...")

results = []

for test_item in tqdm(test_queries, desc="Processing queries"):
    query = test_item["question"]

    # Retrieve contexts
    retrieved_results = retrieval_system.retrieve_topk(query, top_k=5)

    # Extract contexts
    contexts = []
    for result in retrieved_results:
        context_text = result.get('tweet_text', '')
        contexts.append(context_text)

    # Generate response
    try:
        response = response_generator.generate_response(
            user_input=query,
            retrieved_results=retrieved_results,
            conversation_history=[]
        )
    except Exception as e:
        print(f"Error generating response: {e}")
        response = "Unable to generate response"

    # Store results
    results.append({
        "question": query,
        "contexts": contexts,
        "response": response,
        "ground_truth": test_item["ground_truth"],
        "expected_keywords": test_item["expected_keywords"],
        "disaster_type": test_item["disaster_type"],
        "location": test_item["location"],
        "retrieved_metadata": [
            {
                "disaster_type": r.get("disaster_type", ""),
                "location": r.get("extracted_location", ""),
                "score": r.get("score", 0)
            }
            for r in retrieved_results
        ]
    })

print(f"✅ Generated {len(results)} responses")

for result in results:
  print(result)
  print("\n")

# # ============================================================================
# # 8. EVALUATION METRICS
# # ============================================================================

# # Load embedding model for metrics
# print("\n🔧 Loading evaluation model...")
# metric_model = SentenceTransformer("all-MiniLM-L6-v2").to(device)

# class RAGEvaluator:
#     """Evaluate RAG system performance"""

#     def __init__(self, embedding_model):
#         self.embedding_model = embedding_model

#     def compute_similarity(self, text1: str, text2: str) -> float:
#         """Compute cosine similarity between two texts"""
#         emb1 = self.embedding_model.encode([text1], convert_to_tensor=True)
#         emb2 = self.embedding_model.encode([text2], convert_to_tensor=True)

#         similarity = util.pytorch_cos_sim(emb1, emb2)
#         return similarity.item()

#     def context_precision(self, query: str, contexts: List[str], expected_keywords: List[str]) -> float:
#         """
#         Context Precision: Measures if retrieved contexts are relevant to the query
#         """
#         if not contexts:
#             return 0.0

#         precision_scores = []

#         for context in contexts:
#             context_lower = context.lower()

#             # Keyword matching score
#             keyword_matches = sum(1 for kw in expected_keywords if kw.lower() in context_lower)
#             keyword_score = keyword_matches / len(expected_keywords) if expected_keywords else 0

#             # Semantic similarity score
#             semantic_score = self.compute_similarity(query, context)

#             # Combined score (60% semantic, 40% keywords)
#             combined_score = 0.6 * semantic_score + 0.4 * keyword_score
#             precision_scores.append(combined_score)

#         return np.mean(precision_scores)

#     def context_relevancy(self, query: str, contexts: List[str]) -> float:
#         """
#         Context Relevancy: How relevant are the contexts to answering the query?
#         """
#         if not contexts:
#             return 0.0

#         relevancy_scores = []
#         for context in contexts:
#             score = self.compute_similarity(query, context)
#             relevancy_scores.append(score)

#         return np.mean(relevancy_scores)

#     def faithfulness(self, response: str, contexts: List[str]) -> float:
#         """
#         Faithfulness: Is the response grounded in the retrieved contexts?
#         """
#         if not contexts or not response:
#             return 0.0

#         combined_context = " ".join(contexts).lower()

#         # Split response into sentences
#         response_sentences = [s.strip() for s in response.split('.') if s.strip()]

#         if not response_sentences:
#             return 0.0

#         faithful_sentences = 0

#         for sentence in response_sentences:
#             sentence_words = set(sentence.lower().split())
#             # Remove common words
#             sentence_words = sentence_words - {'the', 'is', 'are', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'you', 'your', 'i', 'we', 'can'}

#             if not sentence_words:
#                 continue

#             # Check overlap with context
#             context_words = set(combined_context.split())
#             overlap = len(sentence_words & context_words)

#             if overlap / len(sentence_words) > 0.25:  # 25% overlap threshold
#                 faithful_sentences += 1

#         return faithful_sentences / len(response_sentences)

#     def answer_relevancy(self, query: str, response: str, ground_truth: str) -> float:
#         """
#         Answer Relevancy: How relevant is the answer to the query?
#         """
#         if not response:
#             return 0.0

#         # Query-Response similarity
#         query_sim = self.compute_similarity(query, response)

#         # Response-Ground truth similarity
#         gt_sim = self.compute_similarity(response, ground_truth)

#         # Combined relevancy (70% query match, 30% ground truth match)
#         return 0.7 * query_sim + 0.3 * gt_sim

import re
import numpy as np
from typing import List
from sentence_transformers import SentenceTransformer, util

def clean_text(text: str) -> str:
    if not isinstance(text, str) or not text:
        return ""
    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)
    # Remove twitter handles
    text = re.sub(r'@\w+', ' ', text)
    # Replace non-alphanumeric (keep spaces)
    text = re.sub(r'[^0-9A-Za-z\s]', ' ', text)
    # Normalize whitespace and lowercase
    text = re.sub(r'\s+', ' ', text).strip().lower()
    return text

class RAGEvaluator:
    """
    Improved RAG evaluator:
      - normalizes cosine similarity to [0,1]
      - semantic-based faithfulness per-sentence
      - robust keyword matching after basic cleaning
      - context embedding caching for speed
    """
    def __init__(self, embedding_model: SentenceTransformer, sem_threshold: float = 0.55):
        self.model = embedding_model
        self.sem_threshold = sem_threshold
        # small cache to avoid re-encoding same contexts repeatedly
        self._emb_cache = {}

    def _encode(self, texts: List[str]):
        """Encode list of texts into sentence-transformer tensors (with caching)."""
        # Build list of cleaned texts
        cleaned = [clean_text(t) for t in texts]
        # Create key for cache (join minimal)
        key = "||".join(cleaned)
        if key in self._emb_cache:
            return self._emb_cache[key]
        emb = self.model.encode(cleaned, convert_to_tensor=True)
        self._emb_cache[key] = emb
        return emb

    def compute_similarity(self, text1: str, text2: str) -> float:
        """
        Returns normalized cosine similarity in [0,1]
        """
        t1 = clean_text(text1)
        t2 = clean_text(text2)
        if not t1 or not t2:
            return 0.0
        emb = self.model.encode([t1, t2], convert_to_tensor=True)
        sim = util.pytorch_cos_sim(emb[0], emb[1]).item()
        # Normalize to [0,1]
        sim_norm = (sim + 1.0) / 2.0
        return float(sim_norm)

    def _keyword_score(self, context: str, expected_keywords: List[str]) -> float:
        """
        Keyword matching with relaxed checks:
        - exact word boundary match OR substring match
        - returns fraction matched in [0,1]
        """
        if not expected_keywords:
            return 0.0
        ctx = clean_text(context)
        matches = 0
        for kw in expected_keywords:
            kw_clean = clean_text(kw)
            if not kw_clean:
                continue
            # word boundary match
            if re.search(r'\b' + re.escape(kw_clean) + r'\b', ctx):
                matches += 1
            # substring fallback
            elif kw_clean in ctx:
                matches += 1
        return matches / len(expected_keywords)

    def context_precision(self, query: str, contexts: List[str], expected_keywords: List[str]) -> float:
        """
        Combined relevance score per context:
          - semantic_score (0-1)  weight 0.7
          - keyword_score (0-1)   weight 0.3
        Returns mean combined score across contexts.
        """
        if not contexts:
            return 0.0

        semantic_scores = []
        # encode all contexts at once for speed
        ctx_embs = self._encode(contexts)
        # encode query once
        q_emb = self.model.encode(clean_text(query), convert_to_tensor=True)
        for i, context in enumerate(contexts):
            # semantic similarity (use precomputed)
            try:
                c_emb = ctx_embs[i]
                sem_sim = util.pytorch_cos_sim(q_emb, c_emb).item()
                sem_sim = (sem_sim + 1.0) / 2.0
            except Exception:
                sem_sim = self.compute_similarity(query, context)
            kw_score = self._keyword_score(context, expected_keywords)
            combined = 0.7 * sem_sim + 0.3 * kw_score
            semantic_scores.append(combined)
        return float(np.mean(semantic_scores))

    def context_relevancy(self, query: str, contexts: List[str]) -> float:
        """
        Mean semantic similarity between query and each context (normalized [0,1]).
        """
        if not contexts:
            return 0.0
        ctx_embs = self._encode(contexts)
        q_emb = self.model.encode(clean_text(query), convert_to_tensor=True)
        sims = []
        for i in range(len(contexts)):
            sim = util.pytorch_cos_sim(q_emb, ctx_embs[i]).item()
            sims.append((sim + 1.0) / 2.0)
        return float(np.mean(sims))

    def faithfulness(self, response: str, contexts: List[str]) -> float:
        """
        Semantic faithfulness:
          - Split response into sentences
          - For each sentence, compute max semantic similarity to any context
          - Sentence is faithful if max_sim >= sem_threshold (default 0.55)
          - Return fraction of sentences that are faithful
        """
        if not response or not contexts:
            return 0.0
        # split sentences (lightweight)
        sentences = [s.strip() for s in re.split(r'[.!?]\s*', response) if s.strip()]
        if not sentences:
            return 0.0

        # prepare encodings
        ctx_embs = self._encode(contexts)
        faithful = 0
        for sent in sentences:
            sent_clean = clean_text(sent)
            if not sent_clean:
                continue
            sent_emb = self.model.encode(sent_clean, convert_to_tensor=True)
            # compute similarity against all contexts
            sims = util.pytorch_cos_sim(sent_emb, ctx_embs).cpu().numpy().flatten()
            sims = (sims + 1.0) / 2.0
            max_sim = float(np.max(sims))
            if max_sim >= self.sem_threshold:
                faithful += 1
            else:
                # fallback: lexical overlap (relaxed)
                sent_words = set(sent_clean.split()) - {'the','is','are','a','an','and','or','but','in','on','at','to','for','you','your','i','we','can'}
                combined_ctx = " ".join([clean_text(c) for c in contexts])
                if sent_words:
                    overlap = sum(1 for w in sent_words if re.search(r'\b' + re.escape(w) + r'\b', combined_ctx))
                    if overlap / len(sent_words) >= 0.4:
                        faithful += 1
        return float(faithful / max(1, len(sentences)))

    def answer_relevancy(self, query: str, response: str, ground_truth: str) -> float:
        """
        Combined relevancy:
          - query-response semantic (0-1)
          - response-groundtruth semantic (0-1)
          - weights: 0.7 and 0.3
        """
        if not response:
            return 0.0
        qr = self.compute_similarity(query, response)
        rg = self.compute_similarity(response, ground_truth)
        return float(0.7 * qr + 0.3 * rg)

# ============================================================================
# 9. RUN EVALUATION
# ============================================================================

print("\n📈 Running Evaluation...")
from sentence_transformers import SentenceTransformer
metric_model = SentenceTransformer("all-MiniLM-L6-v2")
evaluator = RAGEvaluator(metric_model, sem_threshold=0.55)

evaluation_results = []

for result in tqdm(results, desc="Evaluating"):
    metrics = {
        "question": result["question"][:80] + "..." if len(result["question"]) > 80 else result["question"],
        "disaster_type": result["disaster_type"],
        "location": result["location"],
        "num_contexts": len(result["contexts"]),
        "context_precision": evaluator.context_precision(
            result["question"],
            result["contexts"],
            result["expected_keywords"]
        ),
        "context_relevancy": evaluator.context_relevancy(
            result["question"],
            result["contexts"]
        ),
        "faithfulness": evaluator.faithfulness(
            result["response"],
            result["contexts"]
        ),
        "answer_relevancy": evaluator.answer_relevancy(
            result["question"],
            result["response"],
            result["ground_truth"]
        ),
        "response": result["response"][:100] + "..." if len(result["response"]) > 100 else result["response"]
    }

    evaluation_results.append(metrics)

# Convert to DataFrame
df_results = pd.DataFrame(evaluation_results)

print("\n✅ Evaluation Complete!")

print("\n" + "="*80)
print("RAG EVALUATION RESULTS")
print("="*80)

# Overall metrics
print("\n📊 OVERALL METRICS:")
print("-" * 80)
print(f"Average Context Precision:  {df_results['context_precision'].mean():.3f}")
print(f"Average Context Relevancy:  {df_results['context_relevancy'].mean():.3f}")
print(f"Average Faithfulness:       {df_results['faithfulness'].mean():.3f}")
print(f"Average Answer Relevancy:   {df_results['answer_relevancy'].mean():.3f}")

# Per disaster type
print("\n📊 METRICS BY DISASTER TYPE:")
print("-" * 80)
for disaster_type in df_results['disaster_type'].unique():
    df_type = df_results[df_results['disaster_type'] == disaster_type]
    print(f"\n{disaster_type.upper()}:")
    print(f"  Context Precision:  {df_type['context_precision'].mean():.3f}")
    print(f"  Context Relevancy:  {df_type['context_relevancy'].mean():.3f}")
    print(f"  Faithfulness:       {df_type['faithfulness'].mean():.3f}")
    print(f"  Answer Relevancy:   {df_type['answer_relevancy'].mean():.3f}")

# Detailed results
print("\n📋 DETAILED RESULTS:")
print("-" * 80)
display_df = df_results[['question', 'disaster_type', 'context_precision',
                         'context_relevancy', 'faithfulness', 'answer_relevancy']]
print(display_df.to_string(index=False))

