# -*- coding: utf-8 -*-
"""setup_chromadb_multimodal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nK3ESkRpb9M_EYyIYnBWXPjfnGc9dc-v
"""

!pip install chromadb

import os
import pandas as pd
from tqdm import tqdm
import torch
from PIL import Image
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.utils import embedding_functions

# ---------------------------------------------------------
# 1. Initialize persistent Chroma client
# ---------------------------------------------------------
client = chromadb.PersistentClient(path="chromadb_store_multimodal")

# ---------------------------------------------------------
# 2. Load or create collection
# ---------------------------------------------------------
collection_name = "crisis_multimodal"
collection = client.get_or_create_collection(name=collection_name)
print(f"✅ Using collection: {collection_name}")

# ---------------------------------------------------------
# 3. Load CLIP model
# ---------------------------------------------------------
print("🧠 Loading CLIP model (openai/clip-vit-base-patch32)...")
device = "cuda" if torch.cuda.is_available() else "cpu"
clip_model = SentenceTransformer("clip-ViT-B-32").to(device)

# ---------------------------------------------------------
# 4. Disaster type extractor
# ---------------------------------------------------------
def get_disaster_type(filename: str) -> str:
    name = os.path.basename(filename).lower()
    if "wildfire" in name:
        return "wildfire"
    elif "earthquake" in name:
        return "earthquake"
    elif "flood" in name:
        return "flood"
    elif "hurricane" in name:
        return "hurricane"
    else:
        return "Other"

import re
import pandas as pd

def normalize_location(loc):
    if not isinstance(loc, str) or loc.strip().lower() == "nan":
        return "Unknown"
    # Remove hashtags, numbers, punctuation, etc.
    loc = re.sub(r"[^a-zA-Z\s,]", "", loc)
    # Split on commas and deduplicate segments
    parts = [p.strip().title() for p in loc.split(",") if p.strip()]
    parts = list(dict.fromkeys(parts))  # preserve order but remove duplicates
    # Join normalized components
    normalized = ", ".join(parts)
    # Handle incomplete tokens
    if not normalized:
        normalized = "Unknown"
    return normalized

base_path = r"/content/drive/MyDrive/Capstone_Prototype/CrisisMMD"
data_dir = os.path.join(base_path, "annotations")

files = [
    "california_wildfires_with_captions_LRR.tsv",
    "mexico_earthquake_with_captions_LRR.tsv",
    "srilanka_floods_with_captions_LRR.tsv",
]

for file in files:
    file_path = os.path.join(data_dir, file)
    if not os.path.exists(file_path):
        print(f"⚠️ File not found: {file_path}")
        continue

    print(f"\n📄 Processing: {file_path}")
    df = pd.read_csv(file_path, sep="\t")

    disaster_type = get_disaster_type(file)
    print(f"🌋 Disaster type: {disaster_type}")

    # Normalize location (overwrite original column)
    df["extracted_locations"] = df["extracted_locations"].apply(normalize_location)

    texts = df["tweet_text"].astype(str).tolist()
    image_paths = [os.path.join(base_path, path) for path in df["image_path"].astype(str).tolist()]
    ids = [f"{file}_{i}" for i in range(len(texts))]

    metadatas = [
        {
            "source_file": file,
            "disaster_type": disaster_type,
            "image_path": img,
            "extracted_location": loc  # now stores normalized location
        }
        for img, loc in zip(image_paths, df["extracted_locations"].tolist())
    ]

    # ---------------------------------------------------------
    # 6. Compute CLIP embeddings (text + image + location)
    # ---------------------------------------------------------
    combined_embeddings = []
    print("🧩 Generating multimodal embeddings...")

    for text, img_path, loc in tqdm(zip(texts, image_paths, df["extracted_locations"]),
                                    total=len(texts)):
        try:
            # Text embedding
            text_emb = clip_model.encode([text], convert_to_tensor=True, device=device)

            # Image embedding
            if os.path.exists(img_path):
                image = Image.open(img_path).convert("RGB")
                img_emb = clip_model.encode([image], convert_to_tensor=True, device=device)
            else:
                img_emb = torch.zeros_like(text_emb)

            # Location embedding
            loc_emb = clip_model.encode([loc], convert_to_tensor=True, device=device)

            # Weighted fusion (text + image + location)
            combined = 0.7 * text_emb + 0.2 * img_emb + 0.1 * loc_emb
            combined_embeddings.append(combined.cpu().numpy().flatten())

        except Exception as e:
            print(f"⚠️ Error processing {img_path}: {e}")
            combined_embeddings.append(torch.zeros(512).numpy())

    # ---------------------------------------------------------
    # 7. Add to ChromaDB
    # ---------------------------------------------------------
    print(f"📥 Adding {len(texts)} multimodal entries to ChromaDB...")
    collection.add(
        documents=texts,
        embeddings=combined_embeddings,
        metadatas=metadatas,
        ids=ids
    )

print("\n✅ All multimodal data successfully added!")
print("💾 Persistent store created at: ./chromadb_store_multimodal")

print("\n📊 Summary:")
print("Total documents:", collection.count())
print("Collections in DB:", [c.name for c in client.list_collections()])

import os
import zipfile

def zip_folder(folder_path, output_path):
    """
    Compresses the entire folder (including subfolders and files) into a ZIP file.

    Args:
        folder_path (str): Path to the folder you want to zip.
        output_path (str): Path for the output .zip file (including filename).
    """
    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(folder_path):
            for file in files:
                file_path = os.path.join(root, file)
                # Store relative paths to preserve folder structure inside the zip
                arcname = os.path.relpath(file_path, start=folder_path)
                zipf.write(file_path, arcname)

    print(f"✅ Folder '{folder_path}' has been zipped as '{output_path}'")

# Example usage
zip_folder("/content/chromadb_store_multimodal", "my_folder.zip")

