# -*- coding: utf-8 -*-
"""Image_Captioner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hc36Qg1rsF8RsoKFehqLxswqKlDANLhG
"""

from google.colab import drive
drive.mount('/content/drive')

from transformers import pipeline

# Load llava-hf model
pipe = pipeline("image-text-to-text", model="llava-hf/llava-1.5-7b-hf")

import glob
import pandas as pd
from PIL import Image
def process_image_hf(image_file):
    with Image.open(image_file) as img:
        messages = [
            {"role": "user", "content": [
                {"type": "image", "image": img},
                {"type": "text", "text": "Describe this image, focusing on disaster-related details."}
            ]}
        ]
        output = pipe(messages, max_new_tokens=128)
        return output[0]["generated_text"]

x=(process_image_hf("/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/data_image/california_wildfires/10_10_2017/917792930315821057_0.jpg"))
x[1]['content']

# df= pd.read_csv("/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/srilanka_floods_final_data.tsv",sep="\t")

# df['image_info'].value_counts()

# df['text_info'].value_counts()

# df = df[(df['text_info'] == 'informative') & (df['image_info'] == 'informative')]

""".

.

.

.
"""

import os
import pandas as pd
from PIL import Image
from transformers import pipeline
from tqdm import tqdm

tsv_path = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_LRR.tsv"
base_dir = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD"
output_path = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_LRR_with_captions.tsv"

df = pd.read_csv(tsv_path, sep="\t")
len(df)

df = df[(df['text_info'] == 'informative') & (df['image_info'] == 'informative')]
len(df)

if os.path.exists(output_path):
    df_out = pd.read_csv(output_path, sep="\t")
    if "image_caption" not in df_out.columns:
        df_out["image_caption"] = None
    print(f"[INFO] Resuming from existing file: {output_path}")
else:
    df_out = df.copy()
    if "image_caption" not in df_out.columns:
        df_out["image_caption"] = None
    print(f"[INFO] Starting fresh captioning")

# df = df.reset_index(drop=True)

def caption_image(image_path, tweet_text=None):
    try:
        with Image.open(image_path) as img:
            # Build prompt
            prompt_text = "Describe this image, focusing on disaster-related details."
            if pd.notna(tweet_text) and isinstance(tweet_text, str) and tweet_text.strip():
                prompt_text += f" The tweet associated with this image says: '{tweet_text}'. Use this as additional context."

            messages = [
                {"role": "user", "content": [
                    {"type": "image", "image": img},
                    {"type": "text", "text": prompt_text}
                ]}
            ]
            output = pipe(messages, max_new_tokens=128)

            # Handle different return shapes
            if isinstance(output, list):
                if isinstance(output[0], dict) and "generated_text" in output[0]:
                    return str(output[0]["generated_text"])
                elif isinstance(output[0], list) and "content" in output[0][1]:
                    # In case it returns a conversation-like structure
                    return str(output[0][1]["content"])
                else:
                    return str(output)
            else:
                return str(output)
    except Exception as e:
        print(f"[ERROR] Failed for {image_path}: {e}")
        return None

for idx in tqdm(range(len(df_out))):
    if pd.isna(df_out.iloc[idx, "image_caption"]):  # Skip already processed
        rel_path = str(df_out.iloc[idx, "image_path"])
        image_path = os.path.join(base_dir, rel_path.lstrip("/"))
        tweet_text = df_out.iloc[idx, "tweet_text"] if "tweet_text" in df_out.columns else None

        if not os.path.exists(image_path):
            print(f"[WARN] Image not found: {image_path}")
            continue

        print(f"[INFO] Processing row {idx} | Image: {rel_path}")
        caption = caption_image(image_path, tweet_text)
        df_out.iloc[idx, "image_caption"] = caption

        # Save progress every 50 images
        if idx % 50 == 0 and idx > 0:
            df_out.to_csv(output_path, sep="\t", index=False)
            print(f"[INFO] Progress saved at row {idx}")

df_out.to_csv(output_path, sep="\t", index=False)
print(f"[DONE] Captions saved to {output_path}")

import os
import pandas as pd
from PIL import Image
from transformers import pipeline
from tqdm import tqdm

# === Load Data ===
tsv_path = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_LRR.tsv"
base_dir = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD"
output_path = "/content/drive/MyDrive/Capstone_Prototype/CrisisMMD/annotations/hurricane_maria_LRR_with_captions.tsv"


df = pd.read_csv(tsv_path, sep="\t")

# Filter only informative samples
df = df[(df['text_info'] == 'informative') & (df['image_info'] == 'informative')]

# If resuming from an existing file
if os.path.exists(output_path):
    df_existing = pd.read_csv(output_path, sep="\t")
    if "image_caption" not in df_existing.columns:
        df_existing["image_caption"] = None
    df = df_existing
    print(f"[INFO] Resuming from existing file: {output_path}")
else:
    if "image_caption" not in df.columns:
        df["image_caption"] = None
    print(f"[INFO] Starting fresh captioning")

# Reset index to avoid KeyError
df = df.reset_index(drop=True)

# === LLaVA Model ===
# pipe = pipeline("image-text-to-text", model="llava-hf/llava-1.5-7b-hf")

# === Captioning Function ===
def caption_image(image_path, tweet_text=None):
    try:
        with Image.open(image_path) as img:
            prompt_text = "Describe this image, focusing on disaster-related details."
            if pd.notna(tweet_text) and isinstance(tweet_text, str) and tweet_text.strip():
                prompt_text += f" The tweet associated with this image says: '{tweet_text}'. Use this as additional context."

            messages = [
                {"role": "user", "content": [
                    {"type": "image", "image": img},
                    {"type": "text", "text": prompt_text}
                ]}
            ]

            output = pipe(messages, max_new_tokens=128)

            if isinstance(output, list):
                if isinstance(output[0], dict) and "generated_text" in output[0]:
                    return str(output[0]["generated_text"])
                elif isinstance(output[0], list) and "content" in output[0][1]:
                    return str(output[0][1]["content"])
                else:
                    return str(output)
            else:
                return str(output)

    except Exception as e:
        print(f"[ERROR] Failed for {image_path}: {e}")
        return None

# === Main Loop ===
for idx in tqdm(range(len(df))):
    if pd.isna(df.loc[idx, "image_caption"]):  # Skip already processed
        rel_path = str(df.loc[idx, "image_path"])
        image_path = os.path.join(base_dir, rel_path.lstrip("/"))
        tweet_text = df.loc[idx, "tweet_text"] if "tweet_text" in df.columns else None

        if not os.path.exists(image_path):
            print(f"[WARN] Image not found: {image_path}")
            continue

        print(f"[INFO] Processing row {idx} | Image: {rel_path}")
        caption = caption_image(image_path, tweet_text)
        df.loc[idx, "image_caption"] = caption

        # Save progress every 50 images
        if idx % 50 == 0 and idx > 0:
            df.to_csv(output_path, sep="\t", index=False)
            print(f"[INFO] Progress saved at row {idx}")

# === Final Save ===
df.to_csv(output_path, sep="\t", index=False)
print(f"[INFO] All captions saved to: {output_path}")

